-- =============================================================================
-- Table: ersh_shield_incidents
-- Purpose: Groups internal/unexpected APEX errors by fingerprint and 30-second
--          time bucket. Each row represents one unique error pattern within one
--          time window. Includes admin resolution tracking.
--
-- @author Angel Flores (Consultant)
-- @created April 11, 2026
-- @ticket ERSH-001
-- =============================================================================


-- =============================================================================
-- 1. TABLE
-- =============================================================================
declare
  l_count pls_integer;
begin
  select count(1)
    into l_count
    from user_tables
   where table_name = 'ERSH_SHIELD_INCIDENTS';

  if l_count = 0 then
    execute immediate q'!
      create table ersh_shield_incidents (
          shield_incident_id  number generated by default on null as identity (start with 1) primary key not null
        -- Link to full error detail in logger_logs
        , logger_log_id       number
        -- APEX correlation: where and who triggered the error
        , application_id      number
        , page_id             number
        , app_user            varchar2(255 char)
        , request             varchar2(255 char)
        , component_type      varchar2(255 char)
        , component_name      varchar2(255 char)
        -- Error detail (safe summary stored only here; full stack lives in logger_logs)
        , ora_sqlcode         number
        , error_summary       varchar2(4000 char)
        -- Deduplication columns
        -- error_fingerprint: SHA-256 hex hash of (application_id|page_id|ora_sqlcode|first 200 chars of message)
        , error_fingerprint   varchar2(64 char)  not null
        -- time_bucket: floor(unix epoch seconds / 30) — groups errors in 30-second windows
        , time_bucket         number             not null
        -- occurrence_count: incremented on each duplicate hit within the same bucket
        , occurrence_count    number default 1   not null
        -- Admin resolution tracking
        , resolved_yn         varchar2(1 char)   default 'N' not null
        , resolved_by         varchar2(60 char)
        , resolved_on         timestamp with local time zone
        , resolution_notes    varchar2(4000 char)
        -- Standard audit columns
        , active_yn           varchar2(1 char) default 'Y' not null
        , created_by          varchar2(60 char) default
                                coalesce(
                                  sys_context('APEX$SESSION', 'app_user')
                                  , regexp_substr(sys_context('userenv', 'client_identifier'), '^[^:]*')
                                  , sys_context('userenv', 'session_user')
                                )
                                not null
        , created_on          timestamp with local time zone default localtimestamp not null
        , last_updated_by     varchar2(60 char)
        , last_updated_on     timestamp with local time zone
        , constraint ck_ersh_shield_incidents_active_yn   check (active_yn   in ('Y', 'N'))
        , constraint ck_ersh_shield_incidents_resolved_yn check (resolved_yn in ('Y', 'N'))
        -- Dedup key: same error pattern within the same 30-second window = same row
        , constraint uk_ersh_shield_incidents_bucket      unique (error_fingerprint, time_bucket)
      )
    !';
  end if;
end;
/


-- =============================================================================
-- 2. INDEXES
-- =============================================================================

-- Admin UI: filter by app + date range
declare
  l_count pls_integer;
begin
  select count(1)
    into l_count
    from user_indexes
   where index_name = 'IDX_ERSH_SHIELD_INCIDENTS_APP'
     and table_name = 'ERSH_SHIELD_INCIDENTS';

  if l_count = 0 then
    execute immediate 'create index idx_ersh_shield_incidents_app on ersh_shield_incidents (application_id, created_on)';
  end if;
end;
/

-- Admin UI: filter unresolved incidents
declare
  l_count pls_integer;
begin
  select count(1)
    into l_count
    from user_indexes
   where index_name = 'IDX_ERSH_SHIELD_INCIDENTS_RESOLVED'
     and table_name = 'ERSH_SHIELD_INCIDENTS';

  if l_count = 0 then
    execute immediate 'create index idx_ersh_shield_incidents_resolved on ersh_shield_incidents (resolved_yn, created_on)';
  end if;
end;
/


-- =============================================================================
-- 3. TRIGGER
-- =============================================================================
create or replace trigger ersh_shield_incidents_trg
  for insert or update on ersh_shield_incidents
  compound trigger

  before each row is
  begin
    if updating then
      :new.last_updated_on := localtimestamp;
      :new.last_updated_by := coalesce(
        sys_context('APEX$SESSION', 'app_user')
        , regexp_substr(sys_context('userenv', 'client_identifier'), '^[^:]*')
        , sys_context('userenv', 'session_user')
      );
    end if;
  end before each row;

end ersh_shield_incidents_trg;
/


-- =============================================================================
-- 4. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table ersh_shield_incidents is ''Groups internal/unexpected APEX errors by fingerprint and 30-second time bucket for admin investigation and resolution tracking.''';
  execute immediate 'comment on column ersh_shield_incidents.shield_incident_id is ''Unique identifier for the incident group (Primary Key).''';
  execute immediate 'comment on column ersh_shield_incidents.logger_log_id is ''ID of the first matching row in logger_logs containing the full error detail.''';
  execute immediate 'comment on column ersh_shield_incidents.application_id is ''APEX application ID where the error occurred.''';
  execute immediate 'comment on column ersh_shield_incidents.page_id is ''APEX page ID where the error occurred.''';
  execute immediate 'comment on column ersh_shield_incidents.app_user is ''APEX application user at the time of the error.''';
  execute immediate 'comment on column ersh_shield_incidents.request is ''APEX request value (e.g. SAVE, DELETE) at the time of the error.''';
  execute immediate 'comment on column ersh_shield_incidents.component_type is ''APEX component type that triggered the error (from apex_error.t_error).''';
  execute immediate 'comment on column ersh_shield_incidents.component_name is ''APEX component name that triggered the error (from apex_error.t_error).''';
  execute immediate 'comment on column ersh_shield_incidents.ora_sqlcode is ''ORA error code from the original error, if applicable.''';
  execute immediate 'comment on column ersh_shield_incidents.error_summary is ''First 4000 chars of the internal error message. Never exposed to end users.''';
  execute immediate 'comment on column ersh_shield_incidents.error_fingerprint is ''SHA-256 hex hash of application_id|page_id|ora_sqlcode|first 200 chars of message. Used as dedup key.''';
  execute immediate 'comment on column ersh_shield_incidents.time_bucket is ''30-second time bucket: floor(unix epoch seconds / 30). Paired with fingerprint as dedup unique key.''';
  execute immediate 'comment on column ersh_shield_incidents.occurrence_count is ''Number of times the same error pattern was hit within this 30-second window.''';
  execute immediate 'comment on column ersh_shield_incidents.resolved_yn is ''Y = admin has reviewed and resolved this incident. N = pending review.''';
  execute immediate 'comment on column ersh_shield_incidents.resolved_by is ''User who marked the incident as resolved.''';
  execute immediate 'comment on column ersh_shield_incidents.resolved_on is ''Timestamp when the incident was marked as resolved.''';
  execute immediate 'comment on column ersh_shield_incidents.resolution_notes is ''Admin notes describing the root cause or fix applied.''';
  execute immediate 'comment on column ersh_shield_incidents.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
  execute immediate 'comment on column ersh_shield_incidents.created_by is ''User who created the record.''';
  execute immediate 'comment on column ersh_shield_incidents.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column ersh_shield_incidents.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column ersh_shield_incidents.last_updated_on is ''Timestamp when the record was last updated.''';
end;
/
