declare
  l_count pls_integer;
begin
  select count(1)
    into l_count
    from user_tables
   where table_name = 'ERSH_CONSTRAINT_LOOKUP';

  if l_count = 0 then
    execute immediate q'!
      create table ersh_constraint_lookup (
          ersh_constraint_lookup_id  number generated by default on null as identity (start with 1) primary key not null
        , constraint_name            varchar2(100 char) not null
        , constraint_message         varchar2(500 char) not null
        , active_yn                  varchar2(1 char) default 'Y' not null
        , created_by                 varchar2(60 char) default
                                       coalesce(
                                         sys_context('APEX$SESSION', 'app_user')
                                         , regexp_substr(sys_context('userenv', 'client_identifier'), '^[^:]*')
                                         , sys_context('userenv', 'session_user')
                                       )
                                       not null
        , created_on                 timestamp with local time zone default localtimestamp not null
        , last_updated_by            varchar2(60 char)
        , last_updated_on            timestamp with local time zone
        , constraint ck_ersh_constraint_lookup_active_yn check (active_yn in ('Y', 'N'))
      )
    !';
  end if;
end;
/


-- -----------------------------------------------------------------------------
-- Constraints
-- -----------------------------------------------------------------------------
declare
  l_count pls_integer;
begin
  select count(1)
    into l_count
    from user_constraints
   where constraint_name = 'UK_ERSH_CONSTRAINT_LOOKUP_NAME'
     and table_name = 'ERSH_CONSTRAINT_LOOKUP';

  if l_count = 0 then
    execute immediate '
      alter table ersh_constraint_lookup
        add constraint uk_ersh_constraint_lookup_name unique (constraint_name)
    ';
  end if;
end;
/


-- -----------------------------------------------------------------------------
-- ERSH-031: active_yn (added after the initial release; idempotent for
-- installs that already had this table before the column existed).
-- -----------------------------------------------------------------------------
declare
  l_count pls_integer;
begin
  select count(1)
    into l_count
    from user_tab_columns
   where table_name  = 'ERSH_CONSTRAINT_LOOKUP'
     and column_name = 'ACTIVE_YN';

  if l_count = 0 then
    execute immediate q'!
      alter table ersh_constraint_lookup
        add active_yn varchar2(1 char) default 'Y' not null
    !';
  end if;
end;
/

declare
  l_count pls_integer;
begin
  select count(1)
    into l_count
    from user_constraints
   where constraint_name = 'CK_ERSH_CONSTRAINT_LOOKUP_ACTIVE_YN'
     and table_name      = 'ERSH_CONSTRAINT_LOOKUP';

  if l_count = 0 then
    execute immediate '
      alter table ersh_constraint_lookup
        add constraint ck_ersh_constraint_lookup_active_yn check (active_yn in (''Y'', ''N''))
    ';
  end if;
end;
/


-- -----------------------------------------------------------------------------
-- Trigger
-- -----------------------------------------------------------------------------
create or replace trigger ersh_constraint_lookup_trg
  for insert or update on ersh_constraint_lookup
  compound trigger

  before each row is
  begin
    if updating then
      :new.last_updated_on := localtimestamp;
      :new.last_updated_by := coalesce(
        sys_context('APEX$SESSION', 'app_user')
        , regexp_substr(sys_context('userenv', 'client_identifier'), '^[^:]*')
        , sys_context('userenv', 'session_user')
      );
    end if;
  end before each row;

end ersh_constraint_lookup_trg;
/


-- -----------------------------------------------------------------------------
-- Comments
-- -----------------------------------------------------------------------------
begin
  execute immediate 'comment on column ersh_constraint_lookup.ersh_constraint_lookup_id is ''Unique identifier for the constraint (Primary Key).''';
  execute immediate 'comment on column ersh_constraint_lookup.constraint_name is ''Name of the constraint.''';
  execute immediate 'comment on column ersh_constraint_lookup.constraint_message is ''Message for the constraint.''';
  execute immediate 'comment on column ersh_constraint_lookup.active_yn is ''Soft-delete flag: Y = active, N = inactive. A deactivated row behaves as if it did not exist (apex_error_handling falls back to the original ORA message).''';
  execute immediate 'comment on column ersh_constraint_lookup.created_by is ''User who created the record.''';
  execute immediate 'comment on column ersh_constraint_lookup.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column ersh_constraint_lookup.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column ersh_constraint_lookup.last_updated_on is ''Timestamp when the record was last updated.''';
  execute immediate 'comment on table ersh_constraint_lookup is ''Lookup table for constraints used in the error handling package.''';
end;
/
