drop table ersh_error_lookup cascade constraints purge;

create table ersh_error_lookup (
    ersh_error_lookup_id         number generated by default on null as identity (start with 1) primary key not null
  , error_code                     varchar2(128 char)
  , ora_sqlcode                    number not null
  , message                        varchar2(4000 char) not null
  , created_by                     varchar2(60 char) default
                                   coalesce(
                                     sys_context('APEX$SESSION', 'app_user')
                                     , regexp_substr(sys_context('userenv', 'client_identifier'), '^[^:]*')
                                     , sys_context('userenv', 'session_user')
                                   )
                                   not null
  , created_on                     timestamp with local time zone default localtimestamp not null
  , last_updated_by                varchar2(60 char)
  , last_updated_on                timestamp with local time zone
  , active_yn                      varchar2(1 char) default 'Y' not null
  , constraint ck_ersh_error_lookup_active_yn check (active_yn in ('Y', 'N'))
);

create unique index uk_ersh_error_lookup_error_code on ersh_error_lookup (error_code);

create or replace trigger ersh_error_lookup_compound_trg
for insert or update on ersh_error_lookup
compound trigger

  before each row is
  begin
    if updating then
      :new.last_updated_on := localtimestamp;
      :new.last_updated_by := coalesce(
                                sys_context('APEX$SESSION', 'app_user')
                                , regexp_substr(sys_context('userenv', 'client_identifier'), '^[^:]*')
                                , sys_context('userenv', 'session_user')
                              );
    end if;
  end before each row;

end ersh_error_lookup_compound_trg;
/

-- column comments
begin
  execute immediate 'comment on column ersh_error_lookup.ersh_error_lookup_id is ''Unique identifier (Primary Key).''';
  execute immediate 'comment on column ersh_error_lookup.error_code is ''Optional: constraint name or custom code (e.g. FK_ersh_CLIENT_DEFAULT_CURRENCY). Null for generic ORA messages.''';
  execute immediate 'comment on column ersh_error_lookup.ora_sqlcode is ''ORA/SQLCODE number (e.g. -20001, -2291).''';
  execute immediate 'comment on column ersh_error_lookup.message is ''User-friendly error message.''';
  execute immediate 'comment on column ersh_error_lookup.active_yn is ''Active flag (Y/N).''';
  --
  execute immediate 'comment on column ersh_error_lookup.created_by is ''User who created the record.''';
  execute immediate 'comment on column ersh_error_lookup.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column ersh_error_lookup.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column ersh_error_lookup.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table ersh_error_lookup is ''Lookup table for ORA errors and custom error codes. Maps ora_sqlcode (and optional error_code) to user-friendly messages.''';
end;
/
