-- =============================================================================
-- Table: ersh_incident_occurrences
-- Purpose: One row per individual error hit, child of ersh_shield_incidents.
--          The parent row is deduplicated by (error_fingerprint, time_bucket)
--          and only keeps the logger_log_id of its first hit; this table keeps
--          every logger_log_id/app_user pair so the reference code shown to
--          any single user can always be traced back to its incident.
--
-- @author Angel Flores (Consultant)
-- @created September 16, 2026
-- @ticket ERSH-010
-- =============================================================================


-- =============================================================================
-- 1. TABLE
-- =============================================================================
declare
  l_count pls_integer;
begin
  select count(1)
    into l_count
    from user_tables
   where table_name = 'ERSH_INCIDENT_OCCURRENCES';

  if l_count = 0 then
    execute immediate q'!
      create table ersh_incident_occurrences (
          occurrence_id       number generated by default on null as identity (start with 1) primary key not null
        , shield_incident_id  number             not null
        -- The reference code shown to the user for THIS hit. Nullable: logger.log_error
        -- runs inside "exception when others then null" in log_and_mask_error, so the
        -- occurrence still has to be recorded (it counts toward occurrence_count) even
        -- when logging failed and no reference code was ever issued.
        , logger_log_id       number
        , app_user            varchar2(255 char)
        , occurred_on         timestamp with local time zone default localtimestamp not null
        -- Standard audit columns
        , active_yn           varchar2(1 char) default 'Y' not null
        , created_by          varchar2(60 char) default
                                coalesce(
                                  sys_context('APEX$SESSION', 'app_user')
                                  , regexp_substr(sys_context('userenv', 'client_identifier'), '^[^:]*')
                                  , sys_context('userenv', 'session_user')
                                )
                                not null
        , created_on          timestamp with local time zone default localtimestamp not null
        , last_updated_by     varchar2(60 char)
        , last_updated_on     timestamp with local time zone
        , constraint ck_ersh_incident_occurrences_active_yn check (active_yn in ('Y', 'N'))
        -- One reference code maps to exactly one occurrence. Multiple NULLs are
        -- allowed (Oracle unique indexes never compare NULL to NULL), so hits
        -- where logger.log_error failed are still accepted.
        , constraint uk_ersh_incident_occurrences_logger_log_id unique (logger_log_id)
        , constraint fk_incident_occurrences_shield_incidents foreign key (shield_incident_id) references ersh_shield_incidents (shield_incident_id)
      )
    !';
  end if;
end;
/


-- =============================================================================
-- 2. INDEXES
-- =============================================================================

-- Support desk lookup: the DEV main pastes the code the user read and searches by
-- it. Already covered by the uk_ersh_incident_occurrences_logger_log_id
-- constraint above (Oracle backs it with an index of the same name), so no
-- separate index is created here.

-- Incident review page: list every occurrence of one incident.
declare
  l_count pls_integer;
begin
  select count(1)
    into l_count
    from user_indexes
   where index_name = 'IDX_ERSH_INCIDENT_OCCURRENCES_INCIDENT'
     and table_name = 'ERSH_INCIDENT_OCCURRENCES';

  if l_count = 0 then
    execute immediate 'create index idx_ersh_incident_occurrences_incident on ersh_incident_occurrences (shield_incident_id)';
  end if;
end;
/


-- =============================================================================
-- 3. TRIGGERS
-- =============================================================================
create or replace trigger ersh_incident_occurrences_trg
  for insert or update on ersh_incident_occurrences
  compound trigger

  before each row is
  begin
    if updating then
      :new.last_updated_on := localtimestamp;
      :new.last_updated_by := coalesce(
        sys_context('APEX$SESSION', 'app_user')
        , regexp_substr(sys_context('userenv', 'client_identifier'), '^[^:]*')
        , sys_context('userenv', 'session_user')
      );
    end if;
  end before each row;

end ersh_incident_occurrences_trg;
/


-- =============================================================================
-- 4. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table ersh_incident_occurrences is ''One row per individual error hit; child of ersh_shield_incidents. Preserves every logger_log_id/app_user pair even when the parent incident is deduplicated.''';
  execute immediate 'comment on column ersh_incident_occurrences.occurrence_id is ''Unique identifier for the occurrence (Primary Key).''';
  execute immediate 'comment on column ersh_incident_occurrences.shield_incident_id is ''Parent incident this occurrence belongs to (Foreign Key to ersh_shield_incidents).''';
  execute immediate 'comment on column ersh_incident_occurrences.logger_log_id is ''ID of the matching row in logger_logs for this specific hit. Same value as the reference code shown to the user. Null when logger.log_error failed for this hit.''';
  execute immediate 'comment on column ersh_incident_occurrences.app_user is ''APEX application user who received this specific reference code.''';
  execute immediate 'comment on column ersh_incident_occurrences.occurred_on is ''Timestamp when this specific hit occurred.''';
  execute immediate 'comment on column ersh_incident_occurrences.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
  execute immediate 'comment on column ersh_incident_occurrences.created_by is ''User who created the record.''';
  execute immediate 'comment on column ersh_incident_occurrences.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column ersh_incident_occurrences.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column ersh_incident_occurrences.last_updated_on is ''Timestamp when the record was last updated.''';
end;
/
