-- =============================================================================
-- Table:   elab_orders
-- Purpose: Child table for the ErrorShield Error Lab demo app (10402). Every
--          constraint here exists to be violated on purpose by one of the
--          lab's buttons, each producing a different ORA code:
--            - ck_elab_orders_quantity  -> ORA-02290 (check violated)
--            - quantity number(5)       -> ORA-01438 (precision exceeded)
--            - fk_elab_orders_customers -> ORA-02291 (parent key not found)
--                                          ORA-02292 (child record found,
--                                          when deleting the parent)
--          ck_elab_orders_quantity is registered in ersh_constraint_lookup by
--          elab_seed.sql (friendly message, no incident);
--          fk_elab_orders_customers is deliberately NOT registered, to show
--          the "unknown constraint -> masked + incident" path.
--
-- @author  Angel Flores (Consultant)
-- @created October 03, 2026
-- @ticket  ERSH-049
-- =============================================================================


-- =============================================================================
-- 1. TABLE
-- =============================================================================
declare
  l_count pls_integer;
begin
  select count(1)                                                   as table_count
    into l_count
    from user_tables
   where table_name = 'ELAB_ORDERS';

  if l_count = 0 then
    execute immediate q'!
      create table elab_orders (
          order_id                     number generated by default on null as identity (start with 1) primary key not null
        , customer_id                  number not null
        , order_date                   date default trunc(sysdate) not null
        , quantity                     number(5) not null
        , status                       varchar2(10 char) default 'NEW' not null
        , notes                        varchar2(50 char)
        , active_yn                    varchar2(1 char) default 'Y' not null
        , created_by                   varchar2(60 char) default
                                        coalesce(
                                          sys_context('APEX$SESSION','app_user')
                                        , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                        , sys_context('userenv','session_user')
                                        )
                                        not null
        , created_on                   timestamp with local time zone default localtimestamp not null
        , last_updated_by              varchar2(60 char)
        , last_updated_on              timestamp with local time zone
        , constraint ck_elab_orders_active_yn check (active_yn in ('Y', 'N'))
        , constraint ck_elab_orders_quantity check (quantity > 0)
        , constraint ck_elab_orders_status check (status in ('NEW', 'PAID', 'SHIPPED'))
        , constraint fk_elab_orders_customers foreign key (customer_id) references elab_customers (customer_id)
      )
    !';
  end if;
end;
/


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
declare
  l_count pls_integer;
begin
  select count(1)                                                   as index_count
    into l_count
    from user_indexes
   where index_name = 'IDX_ELAB_ORDERS_CUSTOMER';

  if l_count = 0 then
    execute immediate 'create index idx_elab_orders_customer on elab_orders (customer_id)';
  end if;
end;
/


-- =============================================================================
-- 3. TRIGGERS
-- =============================================================================
create or replace trigger elab_orders_compound_trg
for insert or update on elab_orders
compound trigger

  before each row is
  begin
    if updating then
      :new.last_updated_on := localtimestamp;
      :new.last_updated_by := coalesce(
                                sys_context('APEX$SESSION','app_user')
                              , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                              , sys_context('userenv','session_user')
                              );
    end if;
  end before each row;

end elab_orders_compound_trg;
/


-- =============================================================================
-- 4. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table elab_orders is ''Error Lab demo (app 10402): child table whose constraints are violated on purpose to feed ErrorShield. Not part of the real product.''';
  execute immediate 'comment on column elab_orders.order_id is ''Unique identifier for the order (Primary Key).''';
  execute immediate 'comment on column elab_orders.customer_id is ''Parent customer (fk_elab_orders_customers). A missing parent raises ORA-02291.''';
  execute immediate 'comment on column elab_orders.order_date is ''Order date.''';
  execute immediate 'comment on column elab_orders.quantity is ''Quantity, number(5) and > 0. Zero/negative raises ORA-02290; 6+ digits raises ORA-01438.''';
  execute immediate 'comment on column elab_orders.status is ''Order status: NEW, PAID or SHIPPED.''';
  execute immediate 'comment on column elab_orders.notes is ''Free-text notes, max 50 chars.''';
  execute immediate 'comment on column elab_orders.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
  execute immediate 'comment on column elab_orders.created_by is ''User who created the record.''';
  execute immediate 'comment on column elab_orders.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column elab_orders.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column elab_orders.last_updated_on is ''Timestamp when the record was last updated.''';
end;
/
