-- =============================================================================
-- Table:   elab_customers
-- Purpose: Parent table for the ErrorShield Error Lab demo app (10402). Every
--          constraint here exists to be violated on purpose by one of the
--          lab's buttons, each producing a different ORA code:
--            - customer_name varchar2(30 char) -> ORA-12899 (value too large)
--            - customer_name not null         -> ORA-01400 (cannot insert NULL)
--            - uk_elab_customers_code         -> ORA-00001 (unique violated)
--          credit_limit backs the business-rule button instead (an order
--          over the limit -> raise_custom_error, shown as written).
--          Lives in the CONSUMER schema, never in the ErrorShield owner
--          schema: the point of the lab is to show errors raised by someone
--          else's app landing in ErrorShield through synonyms.
--
-- @author  Angel Flores (Consultant)
-- @created October 03, 2026
-- @ticket  ERSH-049
-- =============================================================================


-- =============================================================================
-- 1. TABLE
-- =============================================================================
declare
  l_count pls_integer;
begin
  select count(1)                                                   as table_count
    into l_count
    from user_tables
   where table_name = 'ELAB_CUSTOMERS';

  if l_count = 0 then
    execute immediate q'!
      create table elab_customers (
          customer_id                  number generated by default on null as identity (start with 1) primary key not null
        , customer_code                varchar2(10 char) not null
        , customer_name                varchar2(30 char) not null
        , credit_limit                 number(8,2) default 0 not null
        , active_yn                    varchar2(1 char) default 'Y' not null
        , created_by                   varchar2(60 char) default
                                        coalesce(
                                          sys_context('APEX$SESSION','app_user')
                                        , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                        , sys_context('userenv','session_user')
                                        )
                                        not null
        , created_on                   timestamp with local time zone default localtimestamp not null
        , last_updated_by              varchar2(60 char)
        , last_updated_on              timestamp with local time zone
        , constraint ck_elab_customers_active_yn check (active_yn in ('Y', 'N'))
        , constraint uk_elab_customers_code unique (customer_code)
      )
    !';
  end if;
end;
/


-- =============================================================================
-- 2. TRIGGERS
-- =============================================================================
create or replace trigger elab_customers_compound_trg
for insert or update on elab_customers
compound trigger

  before each row is
  begin
    if updating then
      :new.last_updated_on := localtimestamp;
      :new.last_updated_by := coalesce(
                                sys_context('APEX$SESSION','app_user')
                              , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                              , sys_context('userenv','session_user')
                              );
    end if;
  end before each row;

end elab_customers_compound_trg;
/


-- =============================================================================
-- 3. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table elab_customers is ''Error Lab demo (app 10402): parent table whose constraints are violated on purpose to feed ErrorShield. Not part of the real product.''';
  execute immediate 'comment on column elab_customers.customer_id is ''Unique identifier for the customer (Primary Key).''';
  execute immediate 'comment on column elab_customers.customer_code is ''Business code, unique (uk_elab_customers_code). Duplicating it raises ORA-00001.''';
  execute immediate 'comment on column elab_customers.customer_name is ''Customer name, max 30 chars and required. Longer raises ORA-12899; null raises ORA-01400.''';
  execute immediate 'comment on column elab_customers.credit_limit is ''Credit limit. The Error Lab business-rule button refuses any order above it via ersh_error_handler_api.raise_custom_error.''';
  execute immediate 'comment on column elab_customers.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
  execute immediate 'comment on column elab_customers.created_by is ''User who created the record.''';
  execute immediate 'comment on column elab_customers.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column elab_customers.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column elab_customers.last_updated_on is ''Timestamp when the record was last updated.''';
end;
/
